/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Pedido;
import servicos.PedidoServicos;
import servicos.ServicosFactory;

/**
 *
 * @author Alunos
 */
public class GUIManPedido extends javax.swing.JInternalFrame {
    
    DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"Código", "Hambúrguer", "Batata-frita", "Bebida", "Sobremesa", "Cliente", "Total"});
    /**
     * Creates new form GUIManPedido
     */
    public GUIManPedido() {
        initComponents();
        preencherTabela();
        setFrameIcon(new ImageIcon(this.getClass().getResource("/imagens/icon.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlpDados = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedido = new javax.swing.JTable();
        jtPesquisa = new javax.swing.JTextField();
        jcbPesquisa = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbAlterar = new javax.swing.JButton();
        jbPreencher = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tabela de Pedidos");

        jlpDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePedido);

        jtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesquisaKeyReleased(evt);
            }
        });

        jcbPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Hambúrguer", "Batata", "Bebida", "Sobremesa", "Cliente" }));
        jcbPesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbPesquisaItemStateChanged(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/filtrar.png"))); // NOI18N

        jlpDados.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtPesquisa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jcbPesquisa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtPesquisa)
                        .addComponent(jcbPesquisa)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addContainerGap())
        );

        jlpAcoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbPreencher.setText("Preencher");
        jbPreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPreencherActionPerformed(evt);
            }
        });

        jbDeletar.setText("Deletar");
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jlpAcoes.setLayer(jbAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbPreencher, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbDeletar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbPreencher)
                .addGap(51, 51, 51)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpAcoesLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterar)
                    .addComponent(jbPreencher)
                    .addComponent(jbDeletar)
                    .addComponent(jbLimpar))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlpAcoes)
                    .addComponent(jlpDados))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpDados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        alterar();
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbPreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPreencherActionPerformed
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbPreencherActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        deletarCliente();
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limparTabela();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisaKeyReleased
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jtPesquisaKeyReleased

    private void jcbPesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbPesquisaItemStateChanged
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jcbPesquisaItemStateChanged
    private void preencherTabela() {
        try {

            //Buscando objeto ProdutoServicos     
            PedidoServicos ps = ServicosFactory.getPedidoServicos();

            /* Criando um ArrayList<ProdutoVO> vazio
             para receber o ArrayList com os dados */
            ArrayList<Pedido> ped = new ArrayList<>();

            //Recebendo o ArrayList cheio em produtos
            ped = ps.buscarPedidos();

            for (int i = 0; i < ped.size(); i++) {
                dtm.addRow(new String[]{
                    String.valueOf(ped.get(i).getIdPedido()),
                    String.valueOf(ped.get(i).getHamburguer()),
                    String.valueOf(ped.get(i).getBatata()),
                    String.valueOf(ped.get(i).getBebida()),
                    String.valueOf(ped.get(i).getSobremesa()),
                    String.valueOf(ped.get(i).getCliente().getIdCliente()),
                    "R$ "+String.valueOf(ped.get(i).calcularTotal())
                });
            }//fecha for

            /* Adicionando o modelo de tabela 
             com os dados na tabela produto */
            jTablePedido.setModel(dtm);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! " + e.getMessage());
        }//fecha catch
    }
    
    private void limparTabela() {
        /* Para limpar a tabela temos que setar o número de
           linhas para zero no default table model */
        dtm.setNumRows(0);
    }
    
    private void deletarCliente() {
        try {
            int linha = jTablePedido.getSelectedRow();
            if (linha == -1) {
                JOptionPane.showMessageDialog(this,
                        "Escolha uma linha para excluir",
                        "ERRO",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }//fecha if

            String id = jTablePedido.getValueAt(linha, 0).toString();
            PedidoServicos ps = ServicosFactory.getPedidoServicos();
            ps.deletarPedido(Long.parseLong(id));
            JOptionPane.showMessageDialog(
                    this,
                    "Pedido excluido com sucesso!",
                    "OK",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! " + e.getMessage());
        }//fecha catch
    }
    
    private void filtrar() {
        try {            
            if (jtPesquisa.getText().isEmpty()) {
                    preencherTabela();
                    return;
                }else{
                    PedidoServicos ps = ServicosFactory.getPedidoServicos();
                    String pesquisa = (String)jcbPesquisa.getSelectedItem();
                    String query;
                    if(pesquisa.equals("Código")){
                        query = "where idpedido = "+jtPesquisa.getText()+"";
                    }else if(pesquisa.equals("Hambúrguer")){
                        query = "where hamburguer like '%"+jtPesquisa.getText()+"%'";
                    }else if(pesquisa.equals("Batata")){
                        query = "where batata like '%"+jtPesquisa.getText()+"%'";
                    }else if(pesquisa.equals("Bebida")){
                        query = "where bebida like '%"+jtPesquisa.getText()+"%'";
                    }else if(pesquisa.equals("Sobremesa")){
                        query = "where sobremesa like '%"+jtPesquisa.getText()+"%'";
                    }else{
                        query = "where idcliente = "+jtPesquisa.getText()+"";
                    }

                    ArrayList<Pedido> ped = new ArrayList<>();
                    ped = ps.filtrar(query);

                    for(int i=0; i<ped.size(); i++){
                        dtm.addRow(new String[]{
                           String.valueOf(ped.get(i).getIdPedido()),
                           String.valueOf(ped.get(i).getHamburguer()),
                           String.valueOf(ped.get(i).getBatata()),
                           String.valueOf(ped.get(i).getBebida()),
                           String.valueOf(ped.get(i).getSobremesa()),
                           String.valueOf(ped.get(i).getCliente().getIdCliente()),
                           "R$ "+String.valueOf(ped.get(i).calcularTotal())
                        });
                    }
                }
                jTablePedido.setModel(dtm); //NAO PODE ESQUECER
            } catch (Exception e) {
                JOptionPane.showMessageDialog(
                        this,
                        "Erro! " + e.getMessage());
            }
    }
    
    private void alterar() {
        try {
            int linha = jTablePedido.getSelectedRow();
            if (linha == -1) {
                JOptionPane.showMessageDialog(this,
                        "Escolha uma linha para alterar",
                        "ERRO",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }//fecha if
                    
            String id = jTablePedido.getValueAt(linha, 0).toString();
            String hamburguer = jTablePedido.getValueAt(linha, 1).toString();
            String batata = jTablePedido.getValueAt(linha, 2).toString();
            String bebida = jTablePedido.getValueAt(linha, 3).toString();
            String sobremesa = jTablePedido.getValueAt(linha, 4).toString();
            String cliente = jTablePedido.getValueAt(linha, 5).toString();
            
            Pedido p = new Pedido();
            p.setIdPedido(Long.parseLong(id));
            p.setHamburguer(hamburguer);
            p.setBatata(batata);
            p.setBebida(bebida);
            p.setSobremesa(sobremesa);            
            
            Cliente c = new Cliente();
            c.setNome(cliente);    
            
            p.setCliente(c);
            
            PedidoServicos ps = ServicosFactory.getPedidoServicos();
            ps.alterarPedido(p);
            
            JOptionPane.showMessageDialog(this, "Pedido alterado com sucesso!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! " + e.getMessage());
        }//fecha catch
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePedido;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbPreencher;
    private javax.swing.JComboBox jcbPesquisa;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JTextField jtPesquisa;
    // End of variables declaration//GEN-END:variables
}
