/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import java.awt.Image;
import java.awt.Graphics;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author Antonio Guilherme
 * @since 07/05/2019 - 17:16
 * @version 1.0 Beta Shen
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setIcon();
    }
    
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/icon.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/wallpaper.jpg"));
        Image image = icon.getImage();
        jAreaTrabalho = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiHamburguer = new javax.swing.JMenuItem();
        jmiBatata = new javax.swing.JMenuItem();
        jmiBebida = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmCadastro = new javax.swing.JMenu();
        jmiCadCliente = new javax.swing.JMenuItem();
        jmiCadPedido = new javax.swing.JMenuItem();
        jmManutencao = new javax.swing.JMenu();
        jmiManCliente = new javax.swing.JMenuItem();
        jmiManPedido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("McDonalds");

        javax.swing.GroupLayout jAreaTrabalhoLayout = new javax.swing.GroupLayout(jAreaTrabalho);
        jAreaTrabalho.setLayout(jAreaTrabalhoLayout);
        jAreaTrabalhoLayout.setHorizontalGroup(
            jAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        jAreaTrabalhoLayout.setVerticalGroup(
            jAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        jMenuBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setText("Cardápio");

        jmiHamburguer.setText("Hambúrguers");
        jmiHamburguer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiHamburguerActionPerformed(evt);
            }
        });
        jMenu1.add(jmiHamburguer);

        jmiBatata.setText("Batatas");
        jmiBatata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBatataActionPerformed(evt);
            }
        });
        jMenu1.add(jmiBatata);

        jmiBebida.setText("Bebidas");
        jmiBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBebidaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiBebida);

        jMenuItem1.setText("Sobremesas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar.add(jMenu1);

        jmCadastro.setText("Cadastro");

        jmiCadCliente.setText("Cadastrar Cliente");
        jmiCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadClienteActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCadCliente);

        jmiCadPedido.setText("Cadastrar Pedido");
        jmiCadPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadPedidoActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCadPedido);

        jMenuBar.add(jmCadastro);

        jmManutencao.setText("Manutenção");

        jmiManCliente.setText("Tabela de Clientes");
        jmiManCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManClienteActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManCliente);

        jmiManPedido.setText("Tabela de Pedidos");
        jmiManPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManPedidoActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManPedido);

        jMenuBar.add(jmManutencao);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaTrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadClienteActionPerformed
        abrirCadCliente();
    }//GEN-LAST:event_jmiCadClienteActionPerformed

    private void jmiCadPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadPedidoActionPerformed
        abrirCadPedido();
    }//GEN-LAST:event_jmiCadPedidoActionPerformed

    private void jmiManClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManClienteActionPerformed
        abrirManCliente();
    }//GEN-LAST:event_jmiManClienteActionPerformed

    private void jmiManPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManPedidoActionPerformed
        abrirManPedido();
    }//GEN-LAST:event_jmiManPedidoActionPerformed

    private void jmiHamburguerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiHamburguerActionPerformed
        abrirCardHamburguer();
    }//GEN-LAST:event_jmiHamburguerActionPerformed

    private void jmiBatataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBatataActionPerformed
        abrirCardBatata();
    }//GEN-LAST:event_jmiBatataActionPerformed

    private void jmiBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBebidaActionPerformed
        abrirCardBebida();
    }//GEN-LAST:event_jmiBebidaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        abrirCardSobremesa();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void abrirCadCliente(){
        GUICadCliente gcc = new GUICadCliente();
        jAreaTrabalho.add(gcc);
        gcc.setVisible(true);        
    }
    
    private void abrirCadPedido(){
        GUICadPedido gcp = new GUICadPedido();
        jAreaTrabalho.add(gcp);
        gcp.setVisible(true);
    }
    
    private void abrirManCliente(){
        GUIManCliente gmc = new GUIManCliente();
        jAreaTrabalho.add(gmc);
        gmc.setVisible(true);
    }
    
    private void abrirManPedido(){
        GUIManPedido gmp = new GUIManPedido();
        jAreaTrabalho.add(gmp);
        gmp.setVisible(true);
    }
    
    private void abrirCardHamburguer(){
        CardHamburguer ch = new CardHamburguer();
        jAreaTrabalho.add(ch);
        ch.setVisible(true);
    }
    
    private void abrirCardBatata(){
        CardBatata cb = new CardBatata();
        jAreaTrabalho.add(cb);
        cb.setVisible(true);
    }
    
    private void abrirCardBebida(){
        CardBebida cd = new CardBebida();
        jAreaTrabalho.add(cd);
        cd.setVisible(true);
    }
    
    private void abrirCardSobremesa(){
        CardSobremesa cs = new CardSobremesa();
        jAreaTrabalho.add(cs);
        cs.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaTrabalho;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmManutencao;
    private javax.swing.JMenuItem jmiBatata;
    private javax.swing.JMenuItem jmiBebida;
    private javax.swing.JMenuItem jmiCadCliente;
    private javax.swing.JMenuItem jmiCadPedido;
    private javax.swing.JMenuItem jmiHamburguer;
    private javax.swing.JMenuItem jmiManCliente;
    private javax.swing.JMenuItem jmiManPedido;
    // End of variables declaration//GEN-END:variables
}
